export const INDUSTRIES = [
  'E-commerce',
  'SaaS / Tech',
  'Healthcare',
  'Finance',
  'Real Estate',
  'Hospitality',
  'Education',
  'Fashion & Beauty',
  'Food & Beverage',
  'Professional Services',
  'Non-profit',
  'Media & Entertainment',
  'Automotive',
  'Legal',
  'Architecture & Construction',
  'Recruitment & HR',
  'Logistics & Transport',
  'Sports & Fitness',
  'Travel & Tourism',
  'Government & Public Sector',
  'Other',
]

export const CURRENCIES = [
  { code: 'GBP', label: '£ GBP' },
  { code: 'USD', label: '$ USD' },
  { code: 'EUR', label: '€ EUR' },
  { code: 'AUD', label: 'A$ AUD' },
  { code: 'CAD', label: 'C$ CAD' },
  { code: 'AED', label: 'د.إ AED' },
  { code: 'CHF', label: 'Fr CHF' },
  { code: 'HKD', label: 'HK$ HKD' },
  { code: 'INR', label: '₹ INR' },
  { code: 'JPY', label: '¥ JPY' },
  { code: 'NOK', label: 'kr NOK' },
  { code: 'NZD', label: 'NZ$ NZD' },
  { code: 'SEK', label: 'kr SEK' },
  { code: 'SGD', label: 'S$ SGD' },
  { code: 'ZAR', label: 'R ZAR' },
]
